"""Train or fine-tune a YOLOv8 model on synthetic Clash Royale data.

Usage:
    python data/train_yolo.py [--dataset data/dataset.yaml] [--epochs 100] [--base yolov8s.pt]

The script will:
    1. Load a base model (YOLOv8s pretrained or KataCR weights)
    2. Train on the synthetic dataset generated by generate_training_data.py
    3. Save best weights to models/arena_v1/weights/best.pt
    4. Report mAP@0.5 (target >= 0.70)
"""
import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="Train YOLOv8 on Clash Royale data")
    parser.add_argument("--dataset", type=str, default="data/dataset.yaml",
                        help="Path to dataset YAML config")
    parser.add_argument("--base", type=str, default="yolov8s.pt",
                        help="Base model (yolov8s.pt or path to KataCR weights)")
    parser.add_argument("--epochs", type=int, default=100,
                        help="Number of training epochs")
    parser.add_argument("--imgsz", type=int, default=640,
                        help="Input image size for training")
    parser.add_argument("--batch", type=int, default=16,
                        help="Batch size")
    parser.add_argument("--project", type=str, default="models/arena_v1",
                        help="Project directory for saving results")
    parser.add_argument("--name", type=str, default="train",
                        help="Run name within project directory")
    args = parser.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        logger.error("Dataset config not found: %s", dataset_path)
        logger.info("Run generate_training_data.py first, then create data/dataset.yaml")
        sys.exit(1)

    logger.info("Loading base model: %s", args.base)
    model = YOLO(args.base)

    logger.info("Starting training...")
    logger.info("  Dataset: %s", args.dataset)
    logger.info("  Epochs: %d", args.epochs)
    logger.info("  Image size: %d", args.imgsz)
    logger.info("  Batch size: %d", args.batch)

    results = model.train(
        data=str(dataset_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        project=args.project,
        name=args.name,
        exist_ok=True,
        patience=20,       # Early stopping patience
        save=True,
        plots=True,
        verbose=True,
    )

    # Report results
    best_weights = Path(args.project) / args.name / "weights" / "best.pt"
    if best_weights.exists():
        logger.info("Best weights saved to: %s", best_weights)
    else:
        # ultralytics may use a different path structure
        logger.info("Check %s for saved weights", Path(args.project) / args.name)

    # Validate and report mAP
    logger.info("Running validation...")
    val_model = YOLO(str(best_weights)) if best_weights.exists() else model
    metrics = val_model.val(data=str(dataset_path), imgsz=args.imgsz)

    map50 = metrics.box.map50
    map50_95 = metrics.box.map

    logger.info("=" * 60)
    logger.info("Training complete!")
    logger.info("  mAP@0.5:      %.4f (target >= 0.70)", map50)
    logger.info("  mAP@0.5:0.95: %.4f", map50_95)

    if map50 >= 0.70:
        logger.info("Target mAP reached! Model is ready for integration.")
        logger.info("Update config.py: YOLO_MODEL_PATH = '%s'", best_weights)
    else:
        logger.warning("mAP below target. Consider:")
        logger.warning("  - Generating more training data (--count 5000)")
        logger.warning("  - Training for more epochs (--epochs 200)")
        logger.warning("  - Using KataCR weights as base model")


if __name__ == "__main__":
    main()
